### ISSUE TITLE
clip by value

### ISSUE THREAD

**Issue by iperov** [titu1994/keras-adabound#3]
https://github.com/CyberZHG/keras-adabound/blob/master/keras_adabound/optimizers.py

`K.minimum(K.maximum(step, lower_bound), upper_bound)`

will not work?

**Comment by titu1994** [comment]
This works better actually. Dunno why I insisted on using K.clip directly.

**Comment by titu1994** [comment]
Closed via https://github.com/titu1994/keras-adabound/commit/5ce819b6ca1cd95e32d62e268bd2e0c99c069fe8
